### ISSUE TITLE
Dark sidebar theme

### ISSUE THREAD

**Issue by jaredoOS** [brokosz/NotePlan_Themes#14]
Hi brokosz,
So I started playing around with having a dark sidebar, and after lots of experimentation it was more than workable, but there was some alpha version issues (see my notes: https://noteplan.co/n/9FD61532-BA97-4DD0-88EF-7498747A726B). Eduard has just solved the main problems in the next beta (see discussion in #themes in Discord), but there's still going to be a few minor GUI issues. 

I'm happy to post up my dark sidebar theme after the next beta, but as there are a few minor GUI issues out of my control I thought I'd ask if you're happy with it going into bin or if I'd put it into src (would be my first pull request on git, I'm not a coder just know enough to hack into it now then). 

Thanks!

**Comment by brokosz** [comment]
Hey - go ahead and put it in bin.  The src directory really isn’t users by anyone and I should clean it up. On Jan 17, 2023, at 20:53, jaredOS ***@***.***> wrote:﻿
Hi brokosz,
So I started playing around with having a dark sidebar, and after lots of experimentation it was more than workable, but there was some alpha version issues (see my notes: https://noteplan.co/n/9FD61532-BA97-4DD0-88EF-7498747A726B). Eduard has just solved the main problems in the next beta (see discussion in #themes in Discord), but there's still going to be a few minor GUI issues.
I'm happy to post up my dark sidebar theme after the next beta, but as there are a few minor GUI issues out of my control I thought I'd ask if you're happy with it going into bin or if I'd put it into src (would be my first pull request on git, I'm not a coder just know enough to hack into it now then).
Thanks!

**Comment by jaredoOS** [comment]
OK great, will do, fingers crossed I get it right! I'll put a short explainer with or at the top of the file outlining the GUI issues. And will update the theme when Eduard fixes up the remaining ones.
